version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: IdsWfDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    ports: ["5341:80"]

  ids-wf-api:
    build:
      context: .
      dockerfile: src/IDS.WF.API/Dockerfile
    container_name: ids-wf-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=IdsWfDb;Username=postgres;Password=postgres"
      ConnectionStrings__Redis: "redis:6379"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__VHost: "/"
      RabbitMQ__Username: "guest"
      RabbitMQ__Password: "guest"
      Seq__Url: "http://seq"
    depends_on: [postgres, redis, rabbitmq, seq]
    ports: ["7100:8080"]